[mypy]
follow_imports = skip
strict_optional = True
warn_redundant_casts = True
warn_unused_ignores = False
disallow_any_generics = True
check_untyped_defs = True
no_implicit_reexport = True
ignore_missing_imports = True
#disallow_untyped_defs = True

